widgetTheme=widget-themes/original
primaryColor=#FFCC00
secondaryColor=#FFCC22
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@domain.com
loadingLabel=დაელოდეთ...
loginError=შეცდომა
chatHeader=ონლაინ კონსულტაცია
startInfo=საუბრის დაწყებამდე გთხოვთ შეიყვანოთ მონაცები
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=დაწყება
backLabel=უკან
initMessageBody=ოპერატორი გიპასუხებთ მალე
initMessageAuthor=ოპერატორი
chatInputLabel=თქვენი შეკითხვა
timeDaysAgo=დღის უკან
timeHoursAgo=საათის უკან
timeMinutesAgo=წუთის უკან
timeSecondsAgo=წამის უკან
offlineMessage=ოპერატორი გასულია
toggleSoundLabel=ხმის ეფექტი
toggleScrollLabel=აუტო-სქროლი
toggleEmoticonsLabel=ემოციები
toggleAutoShowLabel=აუტო-ჩვენება
toggleFullscreenLabel=სრული ზომა
endChatLabel=დასრულება
endChatConfirmQuestion=დარწმუნებული ხართ?
endChatConfirm=კი
endChatCancel=არა
contactHeader=კონტაქტი
contactInfo=ყველა ოპერატორი დაკავებულია ან გასულია. გამოიყენეთ ქვემოთ მოცემული ფორმა. გამოგვიგზავნეთ ელ-ფოსტით თქვენი შეკითხვა.
contactNameLabel=სახელი
contactMailLabel=ელ-ფოსტა
contactQuestionLabel=შეკითხვა
contactSendLabel=გაგზავნა
contactSuccessHeader=გაიგზავნა წარმატებით
contactSuccessMessage=თქვენი შეკითხვა გაგზავნილია. გმადლობთ!
contactErrorHeader=შეცდომა
contactErrorMessage=თქვენს შეკითხვას გაგზავნის შეცდომა
headerHeight=55
installed=
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
